  #                                      PYTHON ASSIGNMENT

## Write a function called show stars(rows)

In [38]:
row = 5
for i in range(0, row):
    for j in range(0, i + 1):
        print("*", end=' ')
    print("\r")

* 
* * 
* * * 
* * * * 
* * * * * 


## Write a program to remove characters from a string starting from zero up to n and return a new string

In [2]:
sub = ['#', '@', '!', "&", ";"]
string = "r#a@i!n&b;o!w@"
print ("Original String : " , string)
for i in sub :
    string = string.replace(i, '')
print ("Resultant list is : " , str(string))

Original String :  r#a@i!n&b;o!w@
Resultant list is :  rainbow


## Iterate the given list of numbers and print only those numbers which are divisible by 5



In [3]:
x=[33,87,90,55,35]
for i in x:
    if(i%5==0):
        print('the value is :',i)
    else :
        continue

the value is : 90
the value is : 55
the value is : 35


## Write a program to find how many times substring “Hi” appears in the given string

In [4]:
sub=input("enter the string:")
print("the number of times the word hi is displayed is : ",sub.count('hi'))

enter the string:hi hi hi hi hi hi 
the number of times the word hi is displayed is :  6


## Print the following pattern
## 1 
## 2 2 
## 3 3 3 
## 4 4 4 4 
## 5 5 5 5 5


In [42]:
row = 6
for i in range(row):
    
    for j in range(i):
        print(i, end=' ')
    print('')


1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


#                                              LIST

## Python program to interchange first and last elements in a list

In [7]:
def swapP(sl):
    n = len(sl)
      
    # Swapping 
    temp = sl[0]
    sl[0] = sl[n - 1]
    sl[n - 1] = temp
      
    return sl
      
P = [12,98,56,34,21]

print(P)
print("Swapped list: ",swapP(P))

[12, 98, 56, 34, 21]
Swapped list:  [21, 98, 56, 34, 12]


## Python program to swap two elements in a list

In [8]:
def swapL(sl,pos1,pos2):
    n = len(sl)     
    # Swapping 
    temp = sl[pos1]
    sl[pos1] = sl[pos2]
    sl[pos2] = temp
    return sl      

m= [10, 14, 5, 9, 56, 12]
pos1= 3
pos2= 5

print(m)
print("Swapped list: ",swapL(m,pos1-1,pos2-1))


[10, 14, 5, 9, 56, 12]
Swapped list:  [10, 14, 56, 9, 5, 12]


## Python  Ways to find length of list

In [10]:
var = ['cricket','badminton','hockey','football']
size = len(var)
print(size)

4


## Maximum of two numbers in Python

In [11]:
n = [0,8,5,3,67]

  
maxi = max(n )
print(maxi)

67


## Minimum of two numbers in Python

In [12]:
n = [390,456,83,23]

  
mini = min(n)
print(mini)

23


## STRING

## Python program to check whether the string is Symmetrical or Palindrome

In [16]:
inp=(input("enter the string:"))
a=n[::-1]
if a==n:
    print('the given string is a pallindrome')
else:
    print('it is not a pallindrome')


enter the string:well
it is not a pallindrome


## Reverse words in a given String in Python

In [17]:
string = "Hey Everyone!"

n = string.split()[::-1]
l = []
for i in n:
    
    l.append(i)

print(" ".join(l))

Everyone! Hey


## Ways to remove i’th character from string in Python

In [19]:
def removechar(str1, n): 
   x = str1[ : n]   
   y = str1[n + 1: ]
   return x + y
if __name__ == '__main__':
   str1 = input("Enter a string ::")
   n = int(input("Enter the index to remove ::"))
   print("The new string is ::")
   print(removechar(str1, n))

Enter a string ::priya
Enter the index to remove ::3
The new string is ::
pria


# TUPLE

## Python program to Find the size of a Tuple

In [20]:
n=(8,9,5,6,7,43)
b=n.__sizeof__()
b

72

## Python – Maximum and Minimum K elements in Tuple

In [21]:
n=(0,8,5,3,6)
x=max(n)
y=min(n)
print(x)
print(y)

8
0


## Python – Sum of tuple elements

In [22]:
n=(5,3,4,3)
a=sum(n)
print(a)

15


## DICTIONARY

## Python | Sort Python Dictionaries by Key or Value

In [23]:
#by keys

d={"key1":"2","key3":"4","key2":"1"}
print(sorted(d))


['key1', 'key2', 'key3']


In [25]:
#by values 

dict1 = {1: 8, 17: 5, 2: 4}
sorted_values = sorted(dict1.values()) 
sorted_dict = {}

for i in sorted_values:
    for k in dict1.keys():
        if dict1[k] == i:
            sorted_dict[k] = dict1[k]
            break

print(sorted_dict)

{2: 4, 17: 5, 1: 8}


## Python dictionary with keys having multiple inputs

In [26]:
import random as r
dict = {}
 
x, y, z =30,45,78
dict[x, y, z] = x + y - z;
 
x, y, z = 3,5,7
dict[x, y, z] = x + y - z;
 
print(dict)

{(30, 45, 78): -3, (3, 5, 7): 1}


# SET

## Find the size of a Set in Python

In [27]:
a={9,6,3,4}
a.__sizeof__()

200

## Iterate over a set in Python

In [28]:
n={0,8,6,4,2,1}
for i in n:
    print('the element is :',i)

the element is : 0
the element is : 1
the element is : 2
the element is : 4
the element is : 6
the element is : 8


# MATRIX

## Python – Assigning Subsequent Rows to Matrix first row elements

In [29]:
list = [[2,7,8], [14,13,15], [7,9,6], [10, 11, 12]]
print("The original list : ",str(list))
res = {list[0][ele] :  list[ele + 1] for ele in range(len(list) - 1)}
print("The Assigned Matrix : ", str(res))

The original list :  [[2, 7, 8], [14, 13, 15], [7, 9, 6], [10, 11, 12]]
The Assigned Matrix :  {2: [14, 13, 15], 7: [7, 9, 6], 8: [10, 11, 12]}


## Adding and Subtracting Matrices in Python

In [30]:
import numpy as np
A = np.array([[3,5], [24,9]])
B = np.array([[7, 5], [9, 7]])
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
print("Addition of two matrix")
print(np.add(A, B))

Printing elements of first matrix
[[ 3  5]
 [24  9]]
Printing elements of second matrix
[[7 5]
 [9 7]]
Addition of two matrix
[[10 10]
 [33 16]]


# FUNCTIONS

## How to get list of parameters name from a function in Python?

In [31]:
def fun(a,c
       ):
    return a**b 
import inspect  
print(inspect.signature(fun))

(a, c)


## How to Print Multiple Arguments in Python?

In [32]:
def a(name, nam1):
    print("hello", name +', ' , nam1)
a("everyone", "welcome")

hello everyone,  welcome
