# INHERITANCE
## SINGLE INHERTANCE

In [1]:
# single inheritance using protected access modifier
class emp:
    def __init__(self,name,income):
        #protected data members initialization
        self._name=name
        self._income=income
class hr(emp):
    def display(self):
        print("NAME:",self._name)
        print("COURSE ID",self._income)
    def dec(self):
        print('ARTIFICIAL INTELLIGENCE')
hrobj=hr('JOHN',456782)
hrobj.display()
hrobj.dec()

NAME: JOHN
COURSE ID 456782
ARTIFICIAL INTELLIGENCE


## MULTILEVEL INHERITANCE

In [2]:
class gfather:
    gfname='A'
    gfage=60
class father(gfather):
    fname='B'
    fage=5
class son(father):
    sname='C'
    sage=1
sobj=son()
print(sobj.gfname,'\n',sobj.gfage)


A 
 60


## MULTIPLE INHERITANCE

In [3]:
class father:
    fname='F'
    fage=28
class mother:
    mname='M'
    mage=27
class son(father,mother):
    sname='C'
    sage=3
sobj=son()
print("FATHER DETAILS:")
print(sobj.fname,"\n",sobj.fage)
print("\n")
print("MOTHER DETAILS:")
print(sobj.mname,"\n",sobj.mage)

FATHER DETAILS:
F 
 28


MOTHER DETAILS:
M 
 27


## HIERARCHIAL INHERITANCE

In [4]:
class university:
    uid=232
    uname="HARVARD UNIVERSITY"
class arts(university):
    aid=786
    aname="HARVARD ARTS & SCIENCE"
class engg(university):
    eid=897
    ename="HARVARD ENGINEERING COLLEGE"
class medical(university):
    mid=331
    mname="HARVARD MEDICAL COLLEGE & HOSPITAL"
class arch(university):
    arid=445
    arname="HARVARD SCHOOL OF ARCHITECTURE"
eobj=engg()
print(eobj.eid,"\n",eobj.ename)

897 
 HARVARD ENGINEERING COLLEGE


## HYBRID INHERITANCE

In [56]:
class GrandPa:
    def __init__(self):
        print("Grand father")

class Father(GrandPa):
    def __init__(self):
        super().__init__()
        print("Father")

class Mother(GrandPa):
    def __init__(self):
        super().__init__()
        print("Mother")


class child(Father, Mother):
    def __init__(self):
        super().__init__()
        print("Child")

c = child()


Grand father
Mother
Father
Child


## ACCESS MODIFIERS

In [5]:
#private inheritance
class emp:
    def __init__(self,eid,name):
        self._eid=eid
        self._name=name
e1=emp(5,'HI')
e1._eid

5

In [6]:
#private data members initialization
class emp:
    def __init__(self,emid,name):
        self.__eid=emid 
        self.__ename=name
e1=emp(1,"k")

# protected data members initialization
class job:
    def __init__(self,name,role):
        self._name=name 
        self._role=role
    def displaydata(self):
        print("name:",self._name)
        print("role:",self._role)
class hr(job):
    print("COLLEGE")
o1=hr('ARJUN','PROFESSOR') 
o1.displaydata()



COLLEGE
name: ARJUN
role: PROFESSOR


In [8]:
#public data members initialization
class emp:
    def __init__(self,name,height,weight):
        self.sname=name # all data members are public by default 
        self.sheight=height # . is used to initialize public data members
        self.sweight=weight
    def display(self):
        print("NAME:",self.sname)
        print("HEIGHT:",self.sheight)
        print("WEIGHT:",self.sweight)
o1=emp('SAM',169,69)
o1.display()

NAME: SAM
HEIGHT: 169
WEIGHT: 69


## NUMPY AGGREGATORS

In [9]:
import numpy as np
x=np.array([[1,3,5,2],[5,3,5,5],[6,8,7,4]])
print(np.max(x),np.min(x),np.sum(x))

8 1 54


In [10]:
m=np.random.randint(1,56,(5,3))
print(m)
print(m.sum())
print("sum row-wise:",np.sum(x,axis=1))
print("sum col-wise:",np.sum(x,axis=0))
print("max element of each col:",np.max(x,axis=0))
print("min element of each col:",np.min(x,axis=0))


[[35 36 44]
 [12 17 21]
 [ 6 35 27]
 [19 42 40]
 [13 22 43]]
412
sum row-wise: [11 18 25]
sum col-wise: [12 14 17 11]
max element of each col: [6 8 7 5]
min element of each col: [1 3 5 2]


In [11]:
import numpy as np
print(np.product([[1,7],[2,4]]))
print(np.mean([[2,6],[6,8]]))
print(np.std([[2,4],[6,4]]))
print(np.var([[2,2],[6,7]]))
x=np.array([[2,4],[6,2]])
print(np.argmax([1,2,3,4]))
print(np.argmin([1,2,3,4]))
b=np.array([True,True,True,False])
print(np.all(b))
print(np.any(b))
print(np.median([1,2,3,4,5]))

56
5.5
1.4142135623730951
5.1875
3
0
False
True
3.0


## COMPARISION,MASKS AND BOOLEAN ARRAYS IN NUMPY

In [12]:
#boolean operations
import numpy as np
x=np.array([1,7,5,3,2])
print(x<2)
print(x>2)
print(x<=2)
print(x>=2)
print(x!=2)
print(x==2)

[ True False False False False]
[False  True  True  True False]
[ True False False False  True]
[False  True  True  True  True]
[ True  True  True  True False]
[False False False False  True]


In [13]:
4*x==(x**6)

array([False, False, False, False, False])

In [14]:
bool(22 and 8)

True

In [15]:
x=np.array([1,3,1,0,1,1],dtype=bool)
y=np.array([1,1,1,0,1,1],dtype=bool)

In [16]:
x&y

array([ True,  True,  True, False,  True,  True])

In [68]:
x|y

array([ True,  True,  True, False,  True,  True])

In [69]:
x!=y

array([False, False, False, False, False,  True])

In [70]:
x^y

array([False, False, False, False, False,  True])

In [71]:
np.all(x) 

False

In [72]:
np.any(y)

True

## EXCEPTION HANDLING

In [17]:
#zero division error
def fun(a,b):
    try:
        c=a+b/(a-b)
    except ZeroDivisionError:
        print("Error due to divided by 0")
        
    else:
        print(c)
    finally:
        print("error handling learnt succesfully")
fun(2,3)      

    

-1.0
error handling learnt succesfully


In [18]:
cgpa=8.5
try:
    if(cgpa>8.5):
        print("distinction")
except SyntaxError:
    print("syntax error")



In [19]:
list1 = ['x',3, 4, 3,-9.6]
try: 
    print ("Second element =",list1[1])
    print ("Sixth element =",list1[5]) #trying to access out of range element
  
except:
    print ("An error occurred")

Second element = 3
An error occurred


In [20]:
def func1(a , b):
    try:
        c = ((a+b) / (a-b))
    except ZeroDivisionError:
        print ("dividing a/b is 0")
    else:
        print (c)  
        
func1(1,1)
func1(2,4)

dividing a/b is 0
-3.0


In [21]:
try:
    raise NameError("dgs") # Raise Error
except NameError:
    print ("exception")
    

exception
